### ISSUE TITLE
whitelist endpoint /version

### ISSUE THREAD

**Issue by tpboudreau-rackspace** [mmi-cookbooks/ele-repose#31]
Nagios check https_api_rax hits pubilc API endpoint `/version` with no auth token.  Other users and processes may as well.  The endpoint needs to be whitelisted in the keystone-v2.cfg.xml file to allow unauthenticated access.

**Comment by drenalin23** [comment]
This has already been done.
https://github.com/mmi-cookbooks/ele-repose/commit/f24a1315da77f22568f7e603f1560dd635577ed8
