### ISSUE TITLE
Increase backend connection timeout to 600 seconds

### ISSUE THREAD

**Issue by tpboudreau-rackspace** [mmi-cookbooks/ele-repose#32]
Currently at 60 seconds -- the Repose limitation is shorter than both the Apache timeout and the backend timeout.. Set it to be longer than both, certainly longer than the Apache timeout.

**Comment by drenalin23** [comment]
This appears to have been done already.
https://github.com/mmi-cookbooks/ele-repose/commit/f24a1315da77f22568f7e603f1560dd635577ed8
