### ISSUE TITLE
fix circle-ci build

### ISSUE THREAD

**Issue by jguice** [mmi-cookbooks/ele-repose#49]
Running into this issue:  https://github.com/berkshelf/berkshelf/issues/1466

Tried the "quick fix" pinning faraday but doesn't seem to work.

Probably need to install chefdk and use berks from there instead. :(

@mburns FYI :)

**Comment by mburns** [comment]
This will probably be a WONTFIX, as we're moving to Travis.

**Comment by jguice** [comment]
Guess this can be revisited in Travis. ;)
