### ISSUE TITLE
enable repose metrics to graphite

### ISSUE THREAD

**Issue by drenalin23** [mmi-cookbooks/ele-repose#56]
# Description
Add a metrics.cfg.xml file to send repose metrics to graphite.

# How
See example in mmi-cookbooks/metrics-repose

# Why 
Allow basic display of graphs with http response codes in grafana.

# TODO
- [ ] ensure `node.name` prepended to metrics
- [ ] Follow on would be to create a repose dashboard and/or graphs in another dashboard.  
 * Fledgling example at http://graphite00.iad.prod.bf.k1k.me/grafana/index.html#/dashboard/db/repose-dashboard

**Comment by drenalin23** [comment]
@rphillips mentions we should pay attention to how we namespace the metrics we send.

**Comment by rphillips** [comment]
Statsd prefixes our metrics by hostname in the `globalPrefix` statsd config, like:

```
messenger0.dfw1.prod.cm.k1k.me.ele
```

Something to keep in mind when we configure this.

**Comment by dimtruck** [comment]
Fixed by https://github.com/mmi-cookbooks/ele-repose/tree/0.3.15 for repose v7 and https://github.com/mmi-cookbooks/ele-repose/pull/66 for v8+
